<a href="https://colab.research.google.com/github/jasmine-tokudome/python-practice/blob/main/Python_2_py.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

四則演算の基礎

In [1]:
1 + 1

2

In [2]:
2 + 3 + 4 + 5

14

In [4]:
7 - 2

5

In [5]:
7 * 6

42

In [6]:
6 * 7

42

In [7]:
6*7

42

In [8]:
9 / 5

1.8

浮動小数点数
数値を桁並びを表す仮数部と小数点の位置を表す指数部に分割して表現する方式。

In [9]:
9 // 5

1

// とすると小数点以下が無視され、整数部のみかえる。

In [10]:
9 % 5

4

%　は余りを返す。倍数かそうじゃないかの分岐をさせたいときなどに便利。

In [11]:
2 ** 3

8

In [12]:
10 ** 100

10000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000

整数オーバーフロー：整数として保持できる最大の値を超えること。他の言語と異なり、PythonはPCのリソースが許す限りどんな大きな数でも扱える。

計算の優先順位

In [13]:
3.75 * 4 - 1

14.0

オペラントの中に浮動小数点と整数が含まれる場合、浮動小数点が優先される。

In [14]:
2 + 3 * 5

17

掛け算が足し算より優先される

In [16]:
(2 + 3) * 5

25

2 + (3 * 5)のように、可読性をあげるために()をつけるのも良い。

複素数

In [17]:
1 + 2j

(1+2j)

虚部はjで示す

In [18]:
(1 + 2j) + (2 + 3j)

(3+5j)

行列

In [19]:
import numpy as np

In [20]:
np.array([[1,2,3],[4,5,6],[7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

numpy　ナムパイ

In [21]:
a = np.array([[1,2],[3,4]])
b = np.array([[2,3],[4,5]])

In [22]:
a + b

array([[3, 5],
       [7, 9]])

In [23]:
c = np.dot(a,b)
c

array([[10, 13],
       [22, 29]])